version: '3'
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    ports:
      - "80:80"  # Expose le port 80 du conteneur au port 80 de l'hôte
    volumes:
      - /home/mahmoud/projet-rt0707/front:/www  # Assure-toi que le chemin correspond à la structure de ton projet Laravel

  # mosquitto:
  #   build: ./mosquitto-docker  # Chemin vers le dossier contenant le Dockerfile
  #   ports:
  #     - "1883:1883"  # Mappez le port MQTT
  #   container_name: mosquitto  # Nom du conteneur
